(TeX-add-style-hook "main"
 (lambda ()
    (LaTeX-add-bibliographies
     "refs"
     "new-name")
    (LaTeX-add-environments
     "condition"
     "example"
     "definition"
     "proposition"
     "theorem"
     "cor"
     "remark")
    (LaTeX-add-labels
     "eq:this-is-very-important-equation"
     "tab:exceptional-table"
     "fig:xxx1"
     "fig:xxxa"
     "fig:xxxb"
     "fig:xxx")
    (TeX-run-style-hooks
     "subcaption"
     "caption"
     "float"
     "longtable"
     "hyperref"
     "url"
     "listings"
     "natbib"
     "geometry"
     "centering"
     "babel"
     "enumitem"
     "xcolor"
     "graphicx"
     "inputenc"
     "utf8"
     "fontenc"
     "T1"
     "amsthm"
     "amssymb"
     "amsfonts"
     "amsmath"
     "times"
     "textcomp"
     "latex2e"
     "art12"
     "article"
     "polish"
     "twoside"
     "12pt"
     "a4paper")))

